//+------------------------------------------------------------------+
//|                                        Tests/Phase10Tests.mq5     |
//|  MITEMSHUB AI MARKET ENGINE — Phase 10 step-1 unit tests.        |
//|                                                                  |
//|  Locks the two Market/ modules extracted from BandBackTests so   |
//|  the production EA does not depend on a test suite:              |
//|    CGarchForecaster — the EGARCH(1,1) estimator.  Reference      |
//|      sigmas are LOCKED: mode 1 (calibrated-fixed, the production |
//|      estimator) against a fixed-params replication, and mode 0   |
//|      (online-SGD) against the REAL Python EGARCHVarianceFore-    |
//|      caster run over the identical literal return sequence       |
//|      (mql5/phase10_garch_reference.py, which self-validates its  |
//|      mode-0 replication against the actual model before print-   |
//|      ing).  Any divergence > 1e-9 relative fails the suite.      |
//|    CBarAggregator — the tick->closed-bar bucketter matching the  |
//|      Python CandleBuilder convention: floor-bucket OHLC, exactly-|
//|      once bar close on bucket crossing, multi-bucket jumps       |
//|      fabricate no empty bars, stale ticks ignored, Reset clears. |
//+------------------------------------------------------------------+
#property strict
#property copyright "Synthetic Indices Bot"
#property version   "1.00"
#property description "MITEMSHUB Phase 10 step-1 unit tests — GarchForecaster + BarAggregator"

#include "../Core/Constants.mqh"
#include "../Market/GarchForecaster.mqh"
#include "../Market/BarAggregator.mqh"

int g_pass = 0;
int g_fail = 0;

void Check(const string name, const bool ok, const string detail = "")
  {
   if(ok)
     {
      g_pass++;
      Print("[PHASE10] PASS  ", name);
     }
   else
     {
      g_fail++;
      Print("[PHASE10] FAIL  ", name, detail != "" ? "  -> " + detail : "");
     }
  }

bool CloseEnough(const double a, const double b, const double tol = 1e-9)
  {
   double scale = MathMax(MathMax(MathAbs(a), MathAbs(b)), 1e-30);
   return(MathAbs(a - b) <= tol * scale);
  }

// Locked reference inputs: identical literals to
// phase10_garch_reference.py (no sin/cos recompute on either side,
// so both languages consume bit-identical doubles).
double G_REF_RETURNS[80] =
  {
   0.0005, 0.0007779671015499846, 0.0005570053533039865, 0.0005002432145488041,
   0.0005692464858060937, 0.00013751058517439194, -0.0008445980621322633, -0.0014563134136898884,
   -0.0009117587665859359, 0.0003406120698112884, 0.0011107099894438872, 0.0009071110156271411,
   0.00035751009549637373, 0.00013421423041776726, 3.1697105894034825e-05, -0.000481788275064698,
   -0.001164474392070138, -0.0011151778777016657, -4.699593494095599e-05, 0.0011234795610746986,
   0.0013140670168591906, 0.0005648871932023594, -0.00017060055273267482, 0.02,
   -0.000399177883165372, -0.0007417600853446207, -0.0009681042534459014, -0.0003777925968684748,
   0.0008161408770081813, 0.0014927662086302398, 0.0009699771047160247, -0.00014162047939929757,
   -0.0007602162699660287, -0.0006605368014311259, -0.00048360035560919925, -0.000564823261758112,
   -0.00040679424633511787, 0.0004140402700241372, 0.001318781195948058, 0.0012808645252601833,
   0.00018941039791001634, -0.015, -0.001087026063313742, -0.0005692514608392948,
   -0.00018007662365619677, -0.00010173459204810374, 0.00020917713091999745, 0.0009160612462746163,
   0.0012718621035032063, 0.0005778032306934236, -0.0007094095951152371, -0.001383243316044514,
   -0.0009354556940354754, -7.542512053445053e-05, 0.00033419041711064555, 0.0003543981693492218,
   0.0005695715640276278, 0.000942578397392732, 0.0007383860829263874, -0.00031042331796967315,
   -0.0013454230945381276, -0.0013210266954662266, -0.00031490135753110804, 0.000605533245130687,
   0.0007556675423947198, 0.000524447409659916, 0.0005181956699485126, 0.03,
   -4.975953647222279e-06, -0.0010050507966567939, -0.0014509363832235726, -0.0007198818644937858,
   0.0005328250207865333, 0.001138341653807619, 0.0008132207110119416, 0.0002907617319668971,
   0.00012585606085254396, -1.89230561712409e-05, -0.0006066701788280452, -0.0012301576851777333,
  };

// Mode-1 calibrated-fixed sigmas (production estimator): generated by
// phase10_garch_reference.py's fixed-params replication of the MQL5
// recursion (R_75 calibration omega=-1.115 alpha=0.077 gamma=0.011 beta=0.918).
double G_REF_SIGMA_M1[80] =
  {
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.015357179670495663, 0.012044271530251154, 0.009613127883236178,
   0.00783326554238276, 0.006492137666387828, 0.005462345525454465, 0.004665902818817699,
   0.004035265689464888, 0.0035374553914072687, 0.0031722097585958503, 0.002874124936791881,
   0.0025864683376737576, 0.002834786849089618, 0.0025789863217009013, 0.0023518698310039314,
   0.0021507721482975427, 0.0019794258724189647, 0.0018398484244878913, 0.0017503461504382312,
   0.0016889340022107238, 0.0032077077588569237, 0.002873399829693948, 0.0026196693925735286,
   0.0023966667184753625, 0.0021850959817846403, 0.00201881324265513, 0.0018791976682626323,
   0.0017694495389848483, 0.0016913534824327258, 0.0016158503531198422, 0.0015296962428656513,
   0.0014880328064053143, 0.0014511796462422005, 0.0013871059925332331, 0.001346908930945389,
   0.0013182355639194067, 0.0012832036341861401, 0.00125219445332383, 0.003451545601790663,
   0.0030511027239724987, 0.0027541778990813628, 0.0025234949991459776, 0.0023102892168690888,
   0.002132026031723774, 0.002007122750746753, 0.001888186406359629, 0.0017655964380713326,
   0.0016540481508771872, 0.0015535700144002746, 0.001485175981349028, 0.0014457813818320462,
  };

// Mode-0 online-SGD sigmas: generated by running the REAL Python
// EGARCHVarianceForecaster over G_REF_RETURNS (the generator
// self-validates its replication against the model first).
double G_REF_SIGMA_M0[80] =
  {
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.02, 0.02, 0.02,
   0.02, 0.01273694317427356, 0.007933619113948357, 0.0060438735782628195,
   0.006240105105710221, 0.008584080434932239, 0.012504773198300883, 0.01793385167934755,
   0.024932355422798178, 0.033779102486661765, 0.04147869931257216, 0.04647402972905922,
   0.04869749855844823, 0.05329596333751793, 0.05129054181285374, 0.049522210715901446,
   0.04779229194735498, 0.04602900877641865, 0.04431219632492373, 0.042940735051569534,
   0.04187226550967654, 0.012444887141752792, 0.022400589134248854, 0.02980200067078841,
   0.03380233650567243, 0.03537966733454485, 0.0356634699503929, 0.035368893392917024,
   0.034858010771924075, 0.03433458889743673, 0.03371747710246399, 0.033008284625646256,
   0.03255934709803957, 0.03207577356136386, 0.03134411503818487, 0.030728473437235535,
   0.030185269497564185, 0.029607318287852544, 0.02905284606577881, 0.036234545856478,
   0.031712924766963566, 0.029363965916599562, 0.028174536446186838, 0.02725373941597341,
   0.0265728061506661, 0.02618158772475133, 0.02573634083282985, 0.025211388299531363,
   0.024691233722814822, 0.024156980870727835, 0.023721033311665304, 0.023500073860044147,
  };

//+------------------------------------------------------------------+
//| TestGarchWarmup — <30 obs gate, sigma = sqrt(long_run_variance)  |
//+------------------------------------------------------------------+
void TestGarchWarmup()
  {
   Print("[PHASE10] --- GarchForecaster warmup ---");
   CGarchForecaster f(1);   // calibrated-fixed, default params
   double sigma = 0.0;
   for(int i = 0; i < 29; i++)
     {
      bool ready = f.Update(0.001, sigma);
      Check("warmup update " + IntegerToString(i + 1) + " not ready",
            !ready, "sigma=" + DoubleToString(sigma, 10));
      Check("warmup sigma == sqrt(long_run_var) == 0.02",
            CloseEnough(sigma, 0.02, 1e-12), "sigma=" + DoubleToString(sigma, 12));
     }
   Check("observations == 29", f.Observations() == 29);
   bool ready = f.Update(0.001, sigma);
   Check("obs 30 recursion ready", ready);
   // NOTE: the warmup sequence feeds 0.001 (not G_REF_RETURNS[29]), so there
   // is no locked reference value here — the exact-number lock lives in
   // TestGarchLocked.  A mild return must decay sigma below the 0.02 long-run.
   Check("obs 30 sigma decays below long-run after a mild return",
         sigma > 0.01 && sigma < 0.02, "sigma=" + DoubleToString(sigma, 14));
  }

//+------------------------------------------------------------------+
//| TestGarchLocked — the cross-language EGARCH lock                 |
//+------------------------------------------------------------------+
void TestGarchLocked()
  {
   Print("[PHASE10] --- GarchForecaster locked reference sigmas ---");
   CGarchForecaster m1(1, -1.115, 0.077, 0.011, 0.918);   // calibrated R_75
   double sigma = 0.0;
   int diffs = 0;
   for(int i = 0; i < 80; i++)
     {
      m1.Update(G_REF_RETURNS[i], sigma);
      if(!CloseEnough(sigma, G_REF_SIGMA_M1[i], 1e-9))
        {
         diffs++;
         if(diffs <= 3)
            Print("  [mode1] i=", IntegerToString(i), " got=", DoubleToString(sigma, 14),
                  " ref=", DoubleToString(G_REF_SIGMA_M1[i], 14));
        }
     }
   Check("mode-1 sigmas match locked reference (all 80)",
         diffs == 0, IntegerToString(diffs) + " diffs");

   CGarchForecaster m0(0);   // online-SGD — real Python forecaster lock
   diffs = 0;
   for(int i = 0; i < 80; i++)
     {
      m0.Update(G_REF_RETURNS[i], sigma);
      if(!CloseEnough(sigma, G_REF_SIGMA_M0[i], 1e-9))
        {
         diffs++;
         if(diffs <= 3)
            Print("  [mode0] i=", IntegerToString(i), " got=", DoubleToString(sigma, 14),
                  " ref=", DoubleToString(G_REF_SIGMA_M0[i], 14));
        }
     }
   Check("mode-0 sigmas match real Python forecaster (all 80)",
         diffs == 0, IntegerToString(diffs) + " diffs");

   Check("mode 0 and mode 1 diverge (SGD blowup vs calibrated decay)",
         !CloseEnough(G_REF_SIGMA_M0[79], G_REF_SIGMA_M1[79], 1e-3),
         "m0=" + DoubleToString(G_REF_SIGMA_M0[79], 6) + " m1=" + DoubleToString(G_REF_SIGMA_M1[79], 6));
  }

//+------------------------------------------------------------------+
//| TestGarchDeterminism — two instances identical; Reset restores    |
//+------------------------------------------------------------------+
void TestGarchDeterminism()
  {
   Print("[PHASE10] --- GarchForecaster determinism + reset ---");
   CGarchForecaster a(1), b(1);
   double sa = 0.0, sb = 0.0;
   bool same = true;
   for(int i = 0; i < 200; i++)
     {
      double r = (i % 7 == 0) ? 0.01 : ((i % 5 == 0) ? -0.006 : 0.0004);
      a.Update(r, sa);
      b.Update(r, sb);
      if(!CloseEnough(sa, sb, 1e-12))
         same = false;
     }
   Check("two identical forecasters identical after 200 updates", same);
   Check("sigma finite and sane after 200 updates", sa > 1e-6 && sa < 1.0);

   CGarchForecaster c(1);
   c.Update(0.001, sa);
   c.Reset();
   Check("reset restores observations", c.Observations() == 0);
   double sigma = 0.0;
   c.Update(0.001, sigma);
   Check("reset restores warmup sigma (log_var re-init)", CloseEnough(sigma, 0.02, 1e-12));
  }

//+------------------------------------------------------------------+
//| TestBarAggregator — OHLC, exactly-once close, jumps, stale ticks  |
//+------------------------------------------------------------------+
void TestBarAggregator()
  {
   Print("[PHASE10] --- BarAggregator ---");
   CBarAggregator agg(300);   // M5
   AggregatedBar bar;
   datetime t0 = D'2026.08.01 00:00:00';

   Check("first tick no close", !agg.OnTick(100.0, t0 + 5));
   Check("same-bucket tick no close", !agg.OnTick(102.0, t0 + 60));
   Check("same-bucket low no close", !agg.OnTick(98.0, t0 + 120));
   Check("same-bucket close no close", !agg.OnTick(101.0, t0 + 290));
   Check("forming bar OHLC correct",
         agg.FormingBar(bar) && bar.open == 100.0 && bar.high == 102.0
         && bar.low == 98.0 && bar.close == 101.0 && bar.tick_count == 4
         && bar.time == t0);

   Check("bucket crossing closes bar", agg.OnTick(103.0, t0 + 300));
   Check("closed bar exactly-once read", agg.ClosedBar(bar));
   Check("closed bar OHLC",
         bar.open == 100.0 && bar.high == 102.0 && bar.low == 98.0
         && bar.close == 101.0 && bar.tick_count == 4 && bar.time == t0);
   Check("closed bar second read empty", !agg.ClosedBar(bar));
   Check("new bar started at crossing tick",
         agg.FormingBar(bar) && bar.open == 103.0 && bar.time == t0 + 300);

   Check("multi-bucket jump closes", agg.OnTick(105.0, t0 + 1200));
   Check("jump closed bar", agg.ClosedBar(bar) && bar.open == 103.0 && bar.close == 103.0);
   Check("jump new bar at new bucket",
         agg.FormingBar(bar) && bar.time == t0 + 1200 && bar.open == 105.0);

   Check("stale tick ignored", !agg.OnTick(1.0, t0 + 60));
   Check("stale tick left bar intact", agg.FormingBar(bar) && bar.open == 105.0);

   agg.Reset();
   Check("reset clears forming bar", !agg.FormingBar(bar));
   Check("reset: first tick re-seeds", !agg.OnTick(50.0, t0 + 2000));
   Check("reset reseeds open/bucket",
         agg.FormingBar(bar) && bar.open == 50.0 && bar.time == t0 + 1800);
  }

//+------------------------------------------------------------------+
//| TestBarAggregatorDeterminism — identical streams, identical bars  |
//+------------------------------------------------------------------+
void TestBarAggregatorDeterminism()
  {
   Print("[PHASE10] --- BarAggregator determinism ---");
   CBarAggregator a(300), b(300);
   AggregatedBar ba, bb;
   datetime base = D'2026.08.02 00:00:00';
   int closed = 0;
   for(int i = 0; i < 500; i++)
     {
      double price = 100.0 + 0.001 * (i % 97) + ((i % 11 == 0) ? 0.2 : 0.0);
      datetime t = base + i * 7;   // ~7s ticks → many M5 closes
      bool closed_a = a.OnTick(price, t);
      bool closed_b = b.OnTick(price, t);
      Check("both aggregators close in lockstep", closed_a == closed_b);
      if(closed_a)
        {
         closed++;
         Check("A closed bar read", a.ClosedBar(ba));
         Check("B closed bar read", b.ClosedBar(bb));
         Check("identical closed bar",
               ba.time == bb.time && CloseEnough(ba.open, bb.open, 1e-12)
               && CloseEnough(ba.high, bb.high, 1e-12)
               && CloseEnough(ba.low, bb.low, 1e-12)
               && CloseEnough(ba.close, bb.close, 1e-12)
               && ba.tick_count == bb.tick_count);
        }
     }
   Check("lockstep produced bars", closed > 5, "closed=" + IntegerToString(closed));
  }

//+------------------------------------------------------------------+
//| Expert initialization                                              |
//+------------------------------------------------------------------+
int OnInit()
  {
   TestGarchWarmup();
   TestGarchLocked();
   TestGarchDeterminism();
   TestBarAggregator();
   TestBarAggregatorDeterminism();
   Print(StringFormat("[PHASE10] === %d passed, %d failed ===", g_pass, g_fail));
   if(g_fail == 0)
      Print("[PHASE10] SUITE PASSED - Phase 10 step-1 complete");
   else
      Print("[PHASE10] SUITE FAILED - Phase 10 step-1 incomplete");
   return(INIT_SUCCEEDED);
  }

void OnTick() { }
