"""Synthetic price data generator for backtesting.

Supports both Deriv CSPRNG-style synthetic indices AND Blueberry Markets'
proprietary synthetic index algorithm.  Each broker has different price
generation mechanisms, spread models, and asset behaviors.

Key differences:
- Deriv: CSPRNG (Mersenne Twister) with GARCH-like variance scheduling
- Blueberry Markets: In-house proprietary algorithm with distinct index classes
  (SYN, SURGE, DROP, LEAP) each with unique behavioral characteristics

Reference:
- Deriv documentation: "The numbers are generated by a cryptographically
  secure random number generator"
- Blueberry Markets: Proprietary algorithmic modeling framework for
  synthetic indices (SYN100, SURGE50, DROP75, LEAP100, etc.)
- Engle (1982) "Autoregressive Conditional Heteroscedasticity"
- Bollerslev (1986) "Generalized ARCH"
"""

from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Iterator

from synthetic_trader.domain import Tick


# ── Broker Type ──────────────────────────────────────────────────


class BrokerType(str, Enum):
    """Supported broker types with different price generation mechanisms."""
    DERIV = "deriv"
    BLUEBERRY = "blueberry"


# ── GARCH State ──────────────────────────────────────────────────


@dataclass
class GARCHParams:
    """Parameters for the GARCH/EGARCH variance scheduling process.

    These are calibrated to match the empirical properties of
    synthetic indices from different brokers:
    - omega: long-run variance intercept
    - alpha: shock magnitude coefficient
    - beta: variance persistence
    - gamma: asymmetry/leverage (negative returns increase vol more)
    """

    omega: float = 0.0000016
    alpha: float = 0.06
    beta: float = 0.92
    gamma: float = -0.02

    @property
    def persistence(self) -> float:
        """Total persistence: alpha + beta + gamma/2."""
        return self.alpha + self.beta + self.gamma / 2.0

    @property
    def long_run_variance(self) -> float:
        """Unconditional (long-run) variance."""
        p = self.persistence
        if p >= 1.0:
            return self.omega / 1e-6
        return self.omega / (1.0 - p)


# ── Spread Model ─────────────────────────────────────────────────


@dataclass
class SpreadModel:
    """Spread model for a synthetic index.

    Different brokers have different spread characteristics:
    - Deriv: Tight, native spreads controlled end-to-end
    - Blueberry: Markups and variance during non-peak hours
    """

    base_spread_pct: float = 0.001  # Base spread as % of price
    spread_noise: float = 0.01     # Random noise added to spread
    peak_hour_spread_mult: float = 1.0   # Spread multiplier during peak hours
    off_peak_spread_mult: float = 1.5    # Spread multiplier during off-peak hours

    def compute_spread(self, price: float, hour: int, rng: random.Random) -> float:
        """Compute spread for a given price and hour."""
        base = price * self.base_spread_pct

        # Apply time-of-day spread multiplier
        # Off-peak: 22:00-06:00 UTC (Asian session)
        if 22 <= hour or hour < 6:
            base *= self.off_peak_spread_mult
        else:
            base *= self.peak_hour_spread_mult

        # Add noise
        noise = rng.random() * self.spread_noise * price
        return base + noise


# ── Blueberry Markets Index Types ────────────────────────────────


class BlueberryIndexType(str, Enum):
    """Blueberry Markets synthetic index types with distinct behaviors."""
    SYN = "syn"       # Standard synthetic — balanced behavior
    SURGE = "surge"   # Momentum-biased — strong directional moves
    DROP = "drop"     # Crash-prone — sudden drops followed by recovery
    LEAP = "leap"     # Trending — sustained directional moves


@dataclass
class BlueberryIndexConfig:
    """Configuration for a Blueberry Markets synthetic index.

    Each index type has unique behavioral characteristics:
    - SYN: Balanced, mean-reverting with moderate volatility
    - SURGE: Momentum-biased, strong trending moves
    - DROP: Crash-prone, sudden drops followed by recovery
    - LEAP: Trending, sustained directional moves with lower reversion
    """
    index_type: BlueberryIndexType
    symbol: str
    initial_price: float
    base_volatility: float
    garch: GARCHParams
    spread: SpreadModel
    # Behavioral modifiers
    momentum_bias: float = 0.0     # -1 to 1: negative = mean-reverting, positive = trending
    crash_probability: float = 0.0  # Probability of sudden crash per tick (DROP indices)
    recovery_speed: float = 0.5    # How fast price recovers after crash (0-1)


# Pre-configured Blueberry Markets index profiles
BLUEBERRY_INDICES: dict[str, BlueberryIndexConfig] = {
    # ── SYN Indices (Standard Synthetic) ──
    "SYN50": BlueberryIndexConfig(
        index_type=BlueberryIndexType.SYN,
        symbol="SYN50",
        initial_price=5000.0,
        base_volatility=0.12,
        garch=GARCHParams(omega=0.0000012, alpha=0.05, beta=0.93, gamma=-0.015),
        spread=SpreadModel(base_spread_pct=0.0008, off_peak_spread_mult=1.3),
        momentum_bias=0.0,
    ),
    "SYN75": BlueberryIndexConfig(
        index_type=BlueberryIndexType.SYN,
        symbol="SYN75",
        initial_price=7500.0,
        base_volatility=0.14,
        garch=GARCHParams(omega=0.0000014, alpha=0.055, beta=0.925, gamma=-0.018),
        spread=SpreadModel(base_spread_pct=0.0009, off_peak_spread_mult=1.35),
        momentum_bias=0.0,
    ),
    "SYN100": BlueberryIndexConfig(
        index_type=BlueberryIndexType.SYN,
        symbol="SYN100",
        initial_price=10000.0,
        base_volatility=0.16,
        garch=GARCHParams(omega=0.0000016, alpha=0.06, beta=0.92, gamma=-0.02),
        spread=SpreadModel(base_spread_pct=0.001, off_peak_spread_mult=1.4),
        momentum_bias=0.0,
    ),

    # ── SURGE Indices (Momentum-Biased) ──
    "SURGE50": BlueberryIndexConfig(
        index_type=BlueberryIndexType.SURGE,
        symbol="SURGE50",
        initial_price=5000.0,
        base_volatility=0.18,
        garch=GARCHParams(omega=0.0000020, alpha=0.08, beta=0.90, gamma=-0.025),
        spread=SpreadModel(base_spread_pct=0.0012, off_peak_spread_mult=1.5),
        momentum_bias=0.3,  # Positive = trending
    ),
    "SURGE75": BlueberryIndexConfig(
        index_type=BlueberryIndexType.SURGE,
        symbol="SURGE75",
        initial_price=7500.0,
        base_volatility=0.20,
        garch=GARCHParams(omega=0.0000022, alpha=0.085, beta=0.895, gamma=-0.028),
        spread=SpreadModel(base_spread_pct=0.0013, off_peak_spread_mult=1.55),
        momentum_bias=0.35,
    ),
    "SURGE100": BlueberryIndexConfig(
        index_type=BlueberryIndexType.SURGE,
        symbol="SURGE100",
        initial_price=10000.0,
        base_volatility=0.22,
        garch=GARCHParams(omega=0.0000025, alpha=0.09, beta=0.89, gamma=-0.03),
        spread=SpreadModel(base_spread_pct=0.0015, off_peak_spread_mult=1.6),
        momentum_bias=0.4,
    ),

    # ── DROP Indices (Crash-Prone) ──
    "DROP50": BlueberryIndexConfig(
        index_type=BlueberryIndexType.DROP,
        symbol="DROP50",
        initial_price=5000.0,
        base_volatility=0.15,
        garch=GARCHParams(omega=0.0000018, alpha=0.07, beta=0.91, gamma=-0.035),
        spread=SpreadModel(base_spread_pct=0.0011, off_peak_spread_mult=1.4),
        momentum_bias=-0.2,  # Negative = mean-reverting after crashes
        crash_probability=0.002,  # 0.2% chance of crash per tick
        recovery_speed=0.6,
    ),
    "DROP75": BlueberryIndexConfig(
        index_type=BlueberryIndexType.DROP,
        symbol="DROP75",
        initial_price=7500.0,
        base_volatility=0.17,
        garch=GARCHParams(omega=0.0000020, alpha=0.075, beta=0.905, gamma=-0.038),
        spread=SpreadModel(base_spread_pct=0.0012, off_peak_spread_mult=1.45),
        momentum_bias=-0.25,
        crash_probability=0.0025,
        recovery_speed=0.55,
    ),
    "DROP100": BlueberryIndexConfig(
        index_type=BlueberryIndexType.DROP,
        symbol="DROP100",
        initial_price=10000.0,
        base_volatility=0.19,
        garch=GARCHParams(omega=0.0000022, alpha=0.08, beta=0.90, gamma=-0.04),
        spread=SpreadModel(base_spread_pct=0.0014, off_peak_spread_mult=1.5),
        momentum_bias=-0.3,
        crash_probability=0.003,
        recovery_speed=0.5,
    ),

    # ── LEAP Indices (Trending) ──
    "LEAP50": BlueberryIndexConfig(
        index_type=BlueberryIndexType.LEAP,
        symbol="LEAP50",
        initial_price=5000.0,
        base_volatility=0.14,
        garch=GARCHParams(omega=0.0000015, alpha=0.055, beta=0.93, gamma=-0.012),
        spread=SpreadModel(base_spread_pct=0.0009, off_peak_spread_mult=1.3),
        momentum_bias=0.25,  # Trending
    ),
    "LEAP75": BlueberryIndexConfig(
        index_type=BlueberryIndexType.LEAP,
        symbol="LEAP75",
        initial_price=7500.0,
        base_volatility=0.16,
        garch=GARCHParams(omega=0.0000018, alpha=0.06, beta=0.925, gamma=-0.015),
        spread=SpreadModel(base_spread_pct=0.001, off_peak_spread_mult=1.35),
        momentum_bias=0.3,
    ),
    "LEAP100": BlueberryIndexConfig(
        index_type=BlueberryIndexType.LEAP,
        symbol="LEAP100",
        initial_price=10000.0,
        base_volatility=0.18,
        garch=GARCHParams(omega=0.0000020, alpha=0.065, beta=0.92, gamma=-0.018),
        spread=SpreadModel(base_spread_pct=0.0012, off_peak_spread_mult=1.4),
        momentum_bias=0.35,
    ),
}


# ── Deriv Index Configurations ──────────────────────────────────


@dataclass
class SyntheticIndexConfig:
    """Configuration for generating a synthetic index.

    Supports both Deriv-style (CSPRNG) and Blueberry Markets-style
    (proprietary algorithm) synthetic indices.
    """

    symbol: str = "R_100"
    broker: BrokerType = BrokerType.DERIV
    initial_price: float = 300.0
    tick_interval_sec: float = 1.0
    garch: GARCHParams = field(default_factory=GARCHParams)
    base_volatility: float = 0.15
    spread: SpreadModel = field(default_factory=SpreadModel)
    # Blueberry-specific fields (ignored for Deriv)
    index_type: BlueberryIndexType | None = None
    momentum_bias: float = 0.0
    crash_probability: float = 0.0
    recovery_speed: float = 0.5
    # Time-of-day volatility multipliers
    hourly_vol_multipliers: dict[int, float] = field(default_factory=lambda: {
        0: 1.2, 1: 1.15, 2: 1.1, 3: 1.05, 4: 1.0, 5: 0.95,
        6: 0.9, 7: 0.95, 8: 1.0, 9: 1.1, 10: 1.15, 11: 1.2,
        12: 1.15, 13: 1.1, 14: 1.2, 15: 1.25, 16: 1.2, 17: 1.15,
        18: 1.1, 19: 1.05, 20: 1.0, 21: 1.05, 22: 1.1, 23: 1.15,
    })

    @classmethod
    def from_blueberry(cls, symbol: str) -> "SyntheticIndexConfig":
        """Create config from a Blueberry Markets index symbol.

        Examples:
            config = SyntheticIndexConfig.from_blueberry("SYN100")
            config = SyntheticIndexConfig.from_blueberry("SURGE50")
            config = SyntheticIndexConfig.from_blueberry("DROP75")
        """
        bb_config = BLUEBERRY_INDICES.get(symbol.upper())
        if bb_config is None:
            raise ValueError(
                f"Unknown Blueberry Markets index: {symbol}. "
                f"Available: {', '.join(sorted(BLUEBERRY_INDICES.keys()))}"
            )
        return cls(
            symbol=bb_config.symbol,
            broker=BrokerType.BLUEBERRY,
            initial_price=bb_config.initial_price,
            garch=bb_config.garch,
            base_volatility=bb_config.base_volatility,
            spread=bb_config.spread,
            index_type=bb_config.index_type,
            momentum_bias=bb_config.momentum_bias,
            crash_probability=bb_config.crash_probability,
            recovery_speed=bb_config.recovery_speed,
        )

    @classmethod
    def from_deriv(cls, symbol: str = "R_100") -> "SyntheticIndexConfig":
        """Create config from a Deriv index symbol."""
        deriv_configs = {
            "R_100": cls(symbol="R_100", initial_price=300.0, base_volatility=0.15),
            "R_75": cls(symbol="R_75", initial_price=350.0, base_volatility=0.12),
            "V75": cls(symbol="V75", initial_price=6000.0, base_volatility=0.18),
            "V100": cls(symbol="V100", initial_price=9000.0, base_volatility=0.20),
        }
        return deriv_configs.get(symbol, cls(symbol=symbol))


# ── Mersenne Twister CSPRNG Wrapper ──────────────────────────────


class DerivCSPRNG:
    """Mersenne Twister CSPRNG wrapper mimicking random number generation.

    Used by both Deriv (direct CSPRNG) and Blueberry Markets
    (proprietary algorithm with different parameters).
    """

    def __init__(self, seed: int | None = None) -> None:
        self.rng = random.Random(seed)
        if seed is None:
            self.rng.seed(int(time.time() * 1000) % (2**32))

    def uniform(self) -> float:
        """Generate a uniform random number in [0, 1)."""
        return self.rng.random()

    def normal(self) -> float:
        """Generate a standard normal variate using Box-Muller transform."""
        u1 = self.uniform()
        u2 = self.uniform()
        return math.sqrt(-2.0 * math.log(max(u1, 1e-10))) * math.cos(2.0 * math.pi * u2)

    def normal_bounded(self, mean: float = 0.0, std: float = 1.0,
                       low: float = -3.0, high: float = 3.0) -> float:
        """Generate a bounded normal variate."""
        z = self.normal()
        z = max(low, min(high, z))
        return mean + std * z


# ── Synthetic Price Generator ────────────────────────────────────


class SyntheticPriceGenerator:
    """Generate synthetic tick data mimicking broker-specific properties.

    Supports both Deriv (CSPRNG with GARCH) and Blueberry Markets
    (proprietary algorithm with index-type-specific behaviors).

    For Blueberry Markets indices:
    - SYN: Balanced, mean-reverting with moderate volatility
    - SURGE: Momentum-biased, strong trending moves
    - DROP: Crash-prone, sudden drops followed by recovery
    - LEAP: Trending, sustained directional moves
    """

    def __init__(self, config: SyntheticIndexConfig | None = None, seed: int | None = None) -> None:
        self.config = config or SyntheticIndexConfig()
        self.csprng = DerivCSPRNG(seed)
        self.garch = self.config.garch

        # State
        self.current_price = self.config.initial_price
        self.current_epoch = 0.0
        self.log_variance = math.log(self.garch.long_run_variance)
        self.observations = 0
        # DROP index state
        self._crash_cooldown = 0  # Ticks to wait after a crash
        self._recovery_target = 0.0  # Price target during recovery

    def generate_ticks(self, n_ticks: int, start_epoch: float = 0.0,
                       start_hour: int = 0) -> list[Tick]:
        """Generate n_ticks of synthetic price data.

        Parameters
        ----------
        n_ticks : int
            Number of ticks to generate.
        start_epoch : float
            Starting epoch timestamp (seconds since 1970-01-01).
        start_hour : int
            Starting hour of day (0-23) for time-of-day effects.

        Returns
        -------
        list[Tick]
            List of Tick objects with symbol, epoch, price, spread,
            tick_direction, and volume_proxy.
        """
        ticks: list[Tick] = []
        epoch = start_epoch
        prev_price = self.current_price
        last_return = 0.0

        for i in range(n_ticks):
            # Determine hour of day for time-of-day effects
            hour = (start_hour + int(epoch / 3600)) % 24
            hour_mult = self.config.hourly_vol_multipliers.get(hour, 1.0)

            # GARCH variance update
            sigma_t = self._update_garch(last_return)

            # Scale volatility by time-of-day effect
            sigma_scaled = sigma_t * hour_mult

            # Generate price increment
            z = self.csprng.normal()
            tick_vol = sigma_scaled * math.sqrt(self.config.tick_interval_sec / 86400)

            # Apply momentum bias for Blueberry indices
            if self.config.momentum_bias != 0 and last_return != 0:
                # Bias the next return in the same direction as momentum
                momentum_component = self.config.momentum_bias * abs(last_return) * 0.1
                z = z + (1.0 if last_return > 0 else -1.0) * momentum_component

            log_return = z * tick_vol

            # Handle DROP index crash behavior
            if self.config.crash_probability > 0:
                log_return = self._apply_crash_behavior(log_return, prev_price)

            # Update price
            new_price = prev_price * math.exp(log_return)

            # Compute spread using broker-specific spread model
            spread = self.config.spread.compute_spread(
                price=prev_price, hour=hour, rng=self.csprng.rng
            )

            # Compute tick direction
            if new_price > prev_price:
                tick_direction = 1
            elif new_price < prev_price:
                tick_direction = -1
            else:
                tick_direction = 0

            # Compute volume proxy
            volume_proxy = 1.0 / self.config.tick_interval_sec + self.csprng.uniform() * 0.5

            tick = Tick(
                symbol=self.config.symbol,
                epoch=epoch,
                price=round(new_price, 5),
                spread=round(spread, 6),
                tick_direction=tick_direction,
                volume_proxy=round(volume_proxy, 4),
            )
            ticks.append(tick)

            last_return = log_return
            prev_price = new_price
            epoch += self.config.tick_interval_sec

        self.current_price = prev_price
        self.current_epoch = epoch

        return ticks

    def generate_ticks_iterator(self, start_epoch: float = 0.0,
                                start_hour: int = 0) -> Iterator[Tick]:
        """Generate ticks as an infinite iterator (for streaming simulation)."""
        epoch = start_epoch
        last_return = 0.0
        while True:
            hour = (start_hour + int(epoch / 3600)) % 24
            hour_mult = self.config.hourly_vol_multipliers.get(hour, 1.0)

            sigma_t = self._update_garch(last_return)
            sigma_scaled = sigma_t * hour_mult

            z = self.csprng.normal()
            tick_vol = sigma_scaled * math.sqrt(self.config.tick_interval_sec / 86400)

            # Apply momentum bias
            if self.config.momentum_bias != 0 and last_return != 0:
                momentum_component = self.config.momentum_bias * abs(last_return) * 0.1
                z = z + (1.0 if last_return > 0 else -1.0) * momentum_component

            log_return = z * tick_vol

            # Handle DROP index crash behavior
            if self.config.crash_probability > 0:
                log_return = self._apply_crash_behavior(log_return, self.current_price)

            new_price = self.current_price * math.exp(log_return)
            spread = self.config.spread.compute_spread(
                price=self.current_price, hour=hour, rng=self.csprng.rng
            )

            if new_price > self.current_price:
                tick_direction = 1
            elif new_price < self.current_price:
                tick_direction = -1
            else:
                tick_direction = 0

            volume_proxy = 1.0 / self.config.tick_interval_sec + self.csprng.uniform() * 0.5

            tick = Tick(
                symbol=self.config.symbol,
                epoch=epoch,
                price=round(new_price, 5),
                spread=round(spread, 6),
                tick_direction=tick_direction,
                volume_proxy=round(volume_proxy, 4),
            )
            yield tick

            last_return = log_return
            self.current_price = new_price
            epoch += self.config.tick_interval_sec

    def _update_garch(self, last_return: float) -> float:
        """Update EGARCH-inspired variance and return current conditional volatility.

        Parameters
        ----------
        last_return : float
            The log-return from the previous tick (0.0 for first tick).
        """
        self.observations += 1

        sigma_sq_prev = math.exp(self.log_variance)
        sigma_prev = math.sqrt(sigma_sq_prev)

        z_prev = last_return / max(sigma_prev, 1e-10)
        shock_magnitude = abs(z_prev) - 0.7979

        log_var_new = (
            self.garch.omega
            + self.garch.alpha * shock_magnitude
            + self.garch.gamma * z_prev
            + self.garch.beta * self.log_variance
        )

        log_var_new = max(-20.0, min(-2.0, log_var_new))
        self.log_variance = log_var_new

        return math.exp(self.log_variance / 2.0)

    def _apply_crash_behavior(self, log_return: float, current_price: float) -> float:
        """Apply crash behavior for DROP indices.

        DROP indices have a probability of sudden large drops,
        followed by gradual recovery toward the pre-crash level.
        """
        # If in recovery mode, bias return toward recovery target
        if self._crash_cooldown > 0:
            self._crash_cooldown -= 1
            if self._recovery_target > 0:
                # Mean-revert toward recovery target
                target_return = math.log(self._recovery_target / max(current_price, 1e-10))
                log_return = log_return * 0.3 + target_return * 0.7 * self.config.recovery_speed
            return log_return

        # Check for crash trigger
        if self.csprng.rng.random() < self.config.crash_probability:
            # Generate a sudden crash: -3% to -8% drop
            crash_magnitude = -(0.03 + self.csprng.rng.random() * 0.05)
            self._crash_cooldown = int(10 / self.config.tick_interval_sec)  # Recovery over ~10 seconds
            self._recovery_target = current_price * 0.95  # Recover to 95% of pre-crash
            return crash_magnitude

        return log_return

    def get_state(self) -> dict:
        """Get current generator state for serialization."""
        return {
            "symbol": self.config.symbol,
            "broker": self.config.broker.value,
            "current_price": self.current_price,
            "current_epoch": self.current_epoch,
            "log_variance": self.log_variance,
            "observations": self.observations,
            "crash_cooldown": self._crash_cooldown,
            "recovery_target": self._recovery_target,
        }

    def set_state(self, state: dict) -> None:
        """Restore generator state from serialization."""
        self.current_price = state["current_price"]
        self.current_epoch = state["current_epoch"]
        self.log_variance = state["log_variance"]
        self.observations = state["observations"]
        self._crash_cooldown = state.get("crash_cooldown", 0)
        self._recovery_target = state.get("recovery_target", 0.0)


# ── Multiple Dataset Generator ──────────────────────────────────


def generate_synthetic_datasets(
    n_datasets: int,
    ticks_per_dataset: int,
    config: SyntheticIndexConfig | None = None,
    base_seed: int = 42,
) -> list[list[Tick]]:
    """Generate multiple independent synthetic datasets for Monte Carlo testing."""
    datasets: list[list[Tick]] = []
    for i in range(n_datasets):
        gen = SyntheticPriceGenerator(config=config, seed=base_seed + i)
        ticks = gen.generate_ticks(ticks_per_dataset)
        datasets.append(ticks)
    return datasets


def generate_multi_symbol_datasets(
    n_datasets: int,
    ticks_per_dataset: int,
    symbols: list[str] | None = None,
    base_seed: int = 42,
) -> list[dict[str, list[Tick]]]:
    """Generate multi-symbol synthetic datasets.

    Supports both Deriv (R_100, R_75) and Blueberry (SYN100, SURGE50) symbols.
    """
    if symbols is None:
        symbols = ["SYN100"]

    datasets: list[dict[str, list[Tick]]] = []
    for i in range(n_datasets):
        dataset: dict[str, list[Tick]] = {}
        for j, sym in enumerate(symbols):
            # Auto-detect broker from symbol
            if sym.upper() in BLUEBERRY_INDICES:
                cfg = SyntheticIndexConfig.from_blueberry(sym)
            elif sym.startswith("R_") or sym.startswith("V"):
                cfg = SyntheticIndexConfig.from_deriv(sym)
            else:
                cfg = SyntheticIndexConfig(symbol=sym)

            gen = SyntheticPriceGenerator(config=cfg, seed=base_seed + i * 100 + j)
            dataset[sym] = gen.generate_ticks(ticks_per_dataset)
        datasets.append(dataset)
    return datasets
