"""Generator fingerprint detection for Deriv synthetic indices.

Each Deriv volatility index (V75, V100, etc.) is generated by a different
CSPRNG instance with different statistical signatures.  V75 and V100 have
different kurtosis, skewness, autocorrelation profiles, and volatility
clustering strength.

This module detects which index is being traded by analyzing the statistical
properties of recent returns, and adjusts model parameters accordingly.

Key insight: While individual ticks are random, the STATISTICAL DISTRIBUTION
of returns differs between indices.  V75 tends to have lower kurtosis and
stronger mean-reversion than V100, which has fatter tails and more momentum.

Output features:
    - fingerprint_id: detected index identifier (0=V75, 1=V100, 2=unknown)
    - fingerprint_confidence: how confident the detection is (0-1)
    - fingerprint_kurtosis: excess kurtosis of recent returns
    - fingerprint_skewness: skewness of recent returns
    - fingerprint_autocorr: first-order autocorrelation of returns
    - fingerprint_vol_of_vol: volatility of volatility (vol clustering strength)
"""

from __future__ import annotations

import json
import math
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class IndexSignature:
    """Statistical signature of a known synthetic index."""
    name: str
    expected_kurtosis: float  # excess kurtosis (0 = normal)
    expected_skewness: float  # skewness (0 = symmetric)
    expected_autocorr: float  # first-order autocorrelation
    expected_vol_of_vol: float  # vol clustering strength
    kurtosis_tolerance: float = 2.0
    skewness_tolerance: float = 0.5
    autocorr_tolerance: float = 0.1
    vol_of_vol_tolerance: float = 0.3


# Known signatures for major Deriv indices (approximate from historical data)
KNOWN_SIGNATURES: list[IndexSignature] = [
    IndexSignature(
        name="R_75",  # Volatility 75
        expected_kurtosis=3.5,
        expected_skewness=0.0,
        expected_autocorr=-0.02,
        expected_vol_of_vol=1.2,
        kurtosis_tolerance=2.0,
    ),
    IndexSignature(
        name="R_100",  # Volatility 100
        expected_kurtosis=5.0,
        expected_skewness=0.0,
        expected_autocorr=-0.01,
        expected_vol_of_vol=1.5,
        kurtosis_tolerance=2.5,
    ),
]


@dataclass
class FingerprintState:
    """Persistent state for the fingerprint detector."""
    return_buffer: list[float] = field(default_factory=list)
    squared_return_buffer: list[float] = field(default_factory=list)
    observations: int = 0
    last_detected_id: int = -1
    last_detected_confidence: float = 0.0
    
    def to_dict(self) -> dict:
        return {
            "return_buffer": self.return_buffer[-500:],
            "squared_return_buffer": self.squared_return_buffer[-500:],
            "observations": self.observations,
            "last_detected_id": self.last_detected_id,
            "last_detected_confidence": self.last_detected_confidence,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> FingerprintState:
        return cls(
            return_buffer=data.get("return_buffer", []),
            squared_return_buffer=data.get("squared_return_buffer", []),
            observations=data.get("observations", 0),
            last_detected_id=data.get("last_detected_id", -1),
            last_detected_confidence=data.get("last_detected_confidence", 0.0),
        )


class GeneratorFingerprintDetector:
    """Detects which synthetic index is being traded by analyzing return statistics.
    
    Parameters
    ----------
    buffer_size : int
        Number of recent returns to analyze (default 200).
    min_observations : int
        Minimum observations before detection is attempted (default 50).
    known_signatures : list[IndexSignature]
        Known index signatures to match against.
    """
    
    def __init__(
        self,
        buffer_size: int = 200,
        min_observations: int = 50,
        known_signatures: list[IndexSignature] | None = None,
    ) -> None:
        self.buffer_size = buffer_size
        self.min_observations = min_observations
        self.known_signatures = known_signatures or KNOWN_SIGNATURES
        self.state = FingerprintState()
    
    def update(self, log_return: float) -> dict[str, float]:
        """Record a new return and compute fingerprint features.
        
        Parameters
        ----------
        log_return : float
            The log-return of the latest price movement.
            
        Returns
        -------
        dict[str, float]
            Fingerprint features to inject into the decision engine.
        """
        self.state.observations += 1
        self.state.return_buffer.append(log_return)
        self.state.squared_return_buffer.append(log_return ** 2)
        
        # Maintain buffer size
        if len(self.state.return_buffer) > self.buffer_size:
            self.state.return_buffer.pop(0)
        if len(self.state.squared_return_buffer) > self.buffer_size:
            self.state.squared_return_buffer.pop(0)
        
        if len(self.state.return_buffer) < self.min_observations:
            return self._default_features()
        
        return self._compute_features()
    
    def _compute_features(self) -> dict[str, float]:
        """Compute fingerprint features from the return buffer."""
        returns = self.state.return_buffer
        n = len(returns)
        
        # Basic statistics
        mean_r = sum(returns) / n
        var_r = sum((r - mean_r) ** 2 for r in returns) / n
        std_r = math.sqrt(max(var_r, 1e-10))
        
        # Excess kurtosis: E[(X-μ)⁴] / σ⁴ - 3
        kurtosis = sum(((r - mean_r) / std_r) ** 4 for r in returns) / n - 3.0
        
        # Skewness: E[(X-μ)³] / σ³
        skewness = sum(((r - mean_r) / std_r) ** 3 for r in returns) / n
        
        # First-order autocorrelation
        if n > 1:
            mean_prod = sum(returns[i] * returns[i-1] for i in range(1, n)) / (n - 1)
            autocorr = (mean_prod - mean_r ** 2) / max(var_r, 1e-10)
        else:
            autocorr = 0.0
        
        # Vol of vol: coefficient of variation of squared returns
        sq_returns = self.state.squared_return_buffer
        mean_sq = sum(sq_returns) / len(sq_returns)
        var_sq = sum((s - mean_sq) ** 2 for s in sq_returns) / len(sq_returns)
        vol_of_vol = math.sqrt(max(var_sq, 1e-10)) / max(mean_sq, 1e-10)
        
        # Match against known signatures
        best_match_id = -1
        best_match_confidence = 0.0
        
        for idx, sig in enumerate(self.known_signatures):
            # Distance in feature space
            kurt_dist = abs(kurtosis - sig.expected_kurtosis) / sig.kurtosis_tolerance
            skew_dist = abs(skewness - sig.expected_skewness) / sig.skewness_tolerance
            autocorr_dist = abs(autocorr - sig.expected_autocorr) / sig.autocorr_tolerance
            vol_dist = abs(vol_of_vol - sig.expected_vol_of_vol) / sig.vol_of_vol_tolerance
            
            # Weighted distance (kurtosis is most discriminative)
            total_dist = (
                0.4 * kurt_dist
                + 0.2 * skew_dist
                + 0.2 * autocorr_dist
                + 0.2 * vol_dist
            )
            
            # Convert distance to confidence (1 / (1 + distance))
            confidence = 1.0 / (1.0 + total_dist)
            
            if confidence > best_match_confidence:
                best_match_confidence = confidence
                best_match_id = idx
        
        self.state.last_detected_id = best_match_id
        self.state.last_detected_confidence = best_match_confidence
        
        return {
            "fingerprint_id": float(best_match_id),
            "fingerprint_confidence": best_match_confidence,
            "fingerprint_kurtosis": kurtosis,
            "fingerprint_skewness": skewness,
            "fingerprint_autocorr": autocorr,
            "fingerprint_vol_of_vol": vol_of_vol,
            "fingerprint_observations": float(n),
        }
    
    def _default_features(self) -> dict[str, float]:
        """Return neutral features during warmup."""
        return {
            "fingerprint_id": -1.0,
            "fingerprint_confidence": 0.0,
            "fingerprint_kurtosis": 0.0,
            "fingerprint_skewness": 0.0,
            "fingerprint_autocorr": 0.0,
            "fingerprint_vol_of_vol": 0.0,
            "fingerprint_observations": float(len(self.state.return_buffer)),
        }
    
    def get_detected_index(self) -> str | None:
        """Get the name of the detected index, or None if uncertain."""
        if self.state.last_detected_id < 0:
            return None
        if self.state.last_detected_confidence < 0.4:
            return None
        return self.known_signatures[self.state.last_detected_id].name
    
    # ── Persistence ────────────────────────────────────────────────
    
    def save(self, path: str | Path) -> None:
        """Persist state to JSON."""
        data = {
            "buffer_size": self.buffer_size,
            "min_observations": self.min_observations,
            "state": self.state.to_dict(),
        }
        Path(path).write_text(json.dumps(data, indent=2), encoding="utf-8")
    
    @classmethod
    def load(cls, path: str | Path) -> GeneratorFingerprintDetector:
        """Restore state from JSON."""
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        detector = cls(
            buffer_size=data.get("buffer_size", 200),
            min_observations=data.get("min_observations", 50),
        )
        detector.state = FingerprintState.from_dict(data.get("state", {}))
        return detector
