"""Drift detection for the online learning pipeline.

Synthetic indices are generated by a CSPRNG with scheduled volatility
changes (e.g. Volatility 75/100 step-ups), so the *distribution* of
price moves shifts over time.  When the variance regime changes, an
online model trained on the old regime starts producing worse
predictions.

This module wraps river's ADWIN (ADaptive WINdowing) drift detector so
the pipeline can:

  1. Detect when the prediction-error distribution shifts (regime change)
  2. Reset the online model's weights so it re-learns the new regime
     instead of fighting stale patterns
  3. Surface drift telemetry (drift_events, last_drift_step) that the
     decision engine uses to temporarily raise the confidence gate

Reference:
- Bifet & Gavalda (2007) "Learning from Time-Changing Data with
  Adaptive Windowing"
"""

from __future__ import annotations

import json
from pathlib import Path

# ── Import-time guard against river's dead dataset payload ────────────
# river.drift.__init__ unconditionally does `from . import datasets`, and
from typing import Any


# river/drift/datasets/__init__.py parses the embedded airline_passengers
# CSV (~20-30s) on EVERY import.  The bridge runs a Python import smoke test
# with an 8s budget before each live snapshot, so this dead import alone
# made every dashboard call fail validation and fall back to "Live bridge
# unavailable".  We only need ADWIN, so stub the datasets subpackage before
# river.drift loads; the stub satisfies `from . import datasets` and nothing
# in this codebase ever reads from it.
try:  # pragma: no cover - river is an optional dependency
    import sys as _sys
    import types as _types

    # Only ADWIN is used.  river.drift.__init__ also imports datasets
    # (airline_passengers CSV parse, ~20s), kswin/page_hinkley (pull in
    # scipy.stats, ~9s) and retrain — none of which we need.  Stub them out
    # so the whole drift subtree imports in ~2.5s instead of ~30s.
    def _river_stub(key: str, attrs: tuple[str, ...] = ()) -> None:
        if key in _sys.modules:
            return
        _m = _types.ModuleType(key)
        for _a in attrs:
            setattr(_m, _a, type(_a, (), {}))
        _sys.modules[key] = _m

    _river_stub("river.drift.datasets")
    _sys.modules["river.drift.datasets"].__path__ = []
    _river_stub("river.drift.datasets.airline_passengers")
    _river_stub("river.drift.kswin", ("KSWIN",))
    _river_stub("river.drift.page_hinkley", ("PageHinkley",))
    _river_stub("river.drift.retrain", ("DriftRetrainingClassifier",))
    _river_stub("river.drift.dummy", ("DummyDriftDetector",))
    _river_stub("river.drift.no_drift", ("NoDrift",))
    _river_stub("river.drift.binary")
    from river.drift import ADWIN
except Exception:  # pragma: no cover
    ADWIN = None  # type: ignore[assignment,misc]


class DriftDetector:
    """Online drift detector wrapping river's ADWIN.

    Feed one numeric value per call — typically the model's absolute
    prediction error ``abs(label - p)``.  ``observe()`` returns True
    exactly once when a drift is detected; the internal window is then
    restarted so the detector adapts to the new regime.

    Parameters
    ----------
    delta : float
        ADWIN sensitivity (0-1).  Lower = more sensitive (detects
        smaller shifts).  Default 0.002.
    grace_period : int
        Samples the detector ignores at the start of each window.
    min_window_length : int
        Minimum window size before drift can be declared.
    """

    def __init__(
        self,
        delta: float = 0.002,
        grace_period: int = 10,
        min_window_length: int = 5,
    ) -> None:
        self.delta = delta
        self.grace_period = grace_period
        self.min_window_length = min_window_length
        self.n_observations = 0
        self.drift_events = 0
        self.last_drift_step: int | None = None
        self.last_value: float | None = None
        self._window = self._new_window()

    def _new_window(self) -> Any:
        if ADWIN is None:
            return None
        return ADWIN(
            delta=self.delta,
            grace_period=self.grace_period,
            min_window_length=self.min_window_length,
        )

    def observe(self, value: float) -> bool:
        """Feed a value; returns True if a drift was just detected."""
        self.n_observations += 1
        self.last_value = value
        if self._window is None:
            return False
        self._window.update(value)
        # river's drift_detected is a one-shot flag consumed on read.
        if self._window.drift_detected:
            self.drift_events += 1
            self.last_drift_step = self.n_observations
            # Fresh window so the detector re-baselines on the new regime.
            self._window = self._new_window()
            return True
        return False

    @property
    def drift_rate(self) -> float:
        """Fraction of observations that triggered a drift."""
        return self.drift_events / max(self.n_observations, 1)

    def steps_since_last_drift(self, total_updates: int) -> int:
        """Number of observations since the most recent drift."""
        if self.last_drift_step is None:
            return total_updates
        return max(0, total_updates - self.last_drift_step)

    # ── Persistence ──────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "delta": self.delta,
            "grace_period": self.grace_period,
            "min_window_length": self.min_window_length,
            "n_observations": self.n_observations,
            "drift_events": self.drift_events,
            "last_drift_step": self.last_drift_step,
            "last_value": self.last_value,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "DriftDetector":
        detector = cls(
            delta=float(data.get("delta", 0.002)),
            grace_period=int(data.get("grace_period", 10)),
            min_window_length=int(data.get("min_window_length", 5)),
        )
        detector.n_observations = int(data.get("n_observations", 0))
        detector.drift_events = int(data.get("drift_events", 0))
        detector.last_drift_step = data.get("last_drift_step")
        detector.last_value = data.get("last_value")
        return detector

    def save(self, path: str | Path) -> None:
        Path(path).write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> "DriftDetector":
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))
