"""EGARCH(1,1) variance forecasting for synthetic indices.

Synthetic indices are generated by a CSPRNG with a GARCH-like variance
scheduling process.  While individual price ticks are independent, the
*magnitude* of movements clusters — high-volatility periods tend to be
followed by high-volatility periods, and vice versa.  This is the ONE
genuinely exploitable property of synthetic indices.

The Exponential GARCH(1,1) model captures this clustering:

    log(σ²_t) = ω + α * [|z_{t-1}| - E|z_{t-1}|] + γ * z_{t-1} + β * log(σ²_{t-1})

Where:
    - ω is the long-run variance intercept
    - α captures the magnitude shock (leverage effect is separate)
    - γ captures asymmetry / leverage (negative returns increase vol more)
    - β is the variance persistence
    - z_t = r_t / σ_t is the standardized return

Key advantages over symmetric GARCH:
    1. Models leverage effect (negative returns → higher vol increase)
    2. No positivity constraints needed (works in log-variance space)
    3. Streaming online updates — no batch retraining

Output features:
    - garch_forecast: one-step-ahead variance forecast (annualized)
    - garch_sigma: current conditional volatility estimate
    - garch_z_score: how extreme current return is vs forecast vol
    - garch_persistence: β + α * (1 - γ²/2) — regime half-life indicator
    - garch_vol_regime: 0=low, 1=normal, 2=high based on forecast vs realized
    - garch_mean_revert_signal: probability of vol mean-reversion in next N bars
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass, field
from pathlib import Path


def ez_student_t(dof: float) -> float:
    """E|z| for a standardized Student-t distribution with ``dof`` degrees of freedom.

    For dof -> inf this converges to the standard-normal value (~0.7979).
    Heavier tails (small dof) give a larger E|z|.
    """
    if dof <= 1.0:
        return 1.0  # E|z| is undefined for dof <= 1 (no finite variance)
    return math.sqrt(dof / math.pi) * math.exp(
        math.lgamma((dof - 1.0) / 2.0) - math.lgamma(dof / 2.0)
    )


@dataclass
class GARCHState:
    """Current state of the EGARCH(1,1) model."""

    omega: float = -2.0        # log(long-run variance) intercept
    alpha: float = 0.10        # magnitude shock coefficient (tuned for synthetic indices)
    gamma: float = -0.05       # asymmetry / leverage coefficient
    beta: float = 0.85         # variance persistence (slightly lower for faster adaptation)
    log_variance: float = -8.0 # current log-variance (matches synthetic index tick scale)
    observations: int = 0
    long_run_variance: float = math.exp(-8.0)  # ~3.4e-4, realistic for synthetic indices

    @property
    def conditional_variance(self) -> float:
        """Current conditional variance σ²."""
        return math.exp(max(-30.0, min(5.0, self.log_variance)))

    @property
    def conditional_volatility(self) -> float:
        """Current conditional volatility σ."""
        return math.exp(max(-30.0, min(5.0, self.log_variance)) / 2.0)

    @property
    def persistence(self) -> float:
        """EGARCH persistence: β + α * (1 - γ²/2).

        Values close to 1.0 indicate high persistence (regime changes slowly).
        Values below 0.8 indicate rapid mean-reversion.
        """
        return self.beta + self.alpha * (1.0 - self.gamma ** 2 / 2.0)

    @property
    def half_life(self) -> float:
        """Estimated half-life of a variance shock in observations.

        Returns infinity if persistence >= 1.0.
        """
        p = self.persistence
        if p >= 1.0 or p <= 0:
            return float("inf")
        return math.log(0.5) / math.log(p)

    @property
    def long_run_vol(self) -> float:
        """Long-run (unconditional) volatility."""
        return math.exp(self.log_variance / 2.0)

    def to_dict(self) -> dict:
        return {
            "omega": self.omega,
            "alpha": self.alpha,
            "gamma": self.gamma,
            "beta": self.beta,
            "log_variance": self.log_variance,
            "observations": self.observations,
            "long_run_variance": self.long_run_variance,
        }

    @classmethod
    def from_dict(cls, data: dict) -> GARCHState:
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


class EGARCHVarianceForecaster:
    """Streaming EGARCH(1,1) variance forecaster.

    Designed for real-time operation on streaming price data.  No batch
    retraining — parameters are updated via online stochastic gradient
    descent with exponential moving average smoothing.

    Parameters
    ----------
    learning_rate : float
        Step size for online parameter updates.  Lower = more stable
        but slower adaptation.  Default 0.01.
    min_observations : int
        Minimum observations before producing forecasts.  Default 30.
    long_run_var_prior : float
        Prior for long-run variance.  Default 0.0004 (= 2% daily vol
        squared, reasonable for synthetic indices).
    persistence_cap : float
        Maximum allowed persistence before soft-capping beta.  Default 0.999.
    vol_regime_low : float
        Threshold for low-vol regime (fraction of long-run vol).  Default 0.7.
    vol_regime_high : float
        Threshold for high-vol regime (fraction of long-run vol).  Default 1.5.
    mean_revert_lookback : int
        Number of observations to estimate mean-reversion probability.  Default 50.
    distribution : str
        Innovation distribution: ``"normal"`` (default) or ``"studentt"``
        (fat-tailed, uses E|z| for a Student-t with ``dof`` degrees of
        freedom in the EGARCH shock term).
    dof : float
        Degrees of freedom used when ``distribution="studentt"``.
    """

    def __init__(
        self,
        learning_rate: float = 0.01,
        min_observations: int = 30,
        long_run_var_prior: float = 0.0004,
        persistence_cap: float = 0.999,
        vol_regime_low: float = 0.7,
        vol_regime_high: float = 1.5,
        mean_revert_lookback: int = 50,
        buffer_size: int = 50,
        distribution: str = "normal",
        dof: float = 5.0,
    ) -> None:
        self.learning_rate = learning_rate
        self.min_observations = min_observations
        self.persistence_cap = persistence_cap
        self.vol_regime_low = vol_regime_low
        self.vol_regime_high = vol_regime_high
        self.mean_revert_lookback = mean_revert_lookback
        self._buffer_size = buffer_size
        # Innovation distribution: "normal" or "studentt" (fat tails).
        # E|z| differs per distribution and scales the EGARCH shock term.
        self.distribution = distribution
        self.dof = dof
        self._ez = ez_student_t(dof) if distribution == "studentt" else 0.7979

        self.state = GARCHState(
            log_variance=math.log(long_run_var_prior),
            long_run_variance=long_run_var_prior,
        )

        # Buffer for initial variance estimation
        self._return_buffer: list[float] = []

        # Running z-score history for mean-reversion probability
        self._z_history: list[float] = []

        # Online gradient accumulator (EMA of squared gradients)
        self._grad_sq_ema: dict[str, float] = {
            "omega": 1e-6, "alpha": 1e-6, "gamma": 1e-6, "beta": 1e-6,
        }

    def update(self, log_return: float) -> dict[str, float]:
        """Process a new log-return and update the model.

        Parameters
        ----------
        log_return : float
            The log-return r_t = ln(P_t / P_{t-1}).

        Returns
        -------
        dict[str, float]
            Forecast features to inject into the decision engine.
        """
        self.state.observations += 1

        # Phase 1: Buffer returns for initial variance estimation
        if self.state.observations <= self._buffer_size:
            self._return_buffer.append(log_return)
            if self.state.observations < self.min_observations:
                return self._default_features()

            # Initialize variance from buffered returns
            if self.state.observations == self._buffer_size:
                mean_sq = sum(r ** 2 for r in self._return_buffer) / len(self._return_buffer)
                self.state.log_variance = math.log(max(mean_sq, 1e-10))
                self.state.long_run_variance = math.exp(self.state.log_variance)

        # Phase 2: EGARCH update
        sigma_t = self.state.conditional_volatility
        z_t = log_return / max(sigma_t, 1e-10)

        # Standardized shock magnitude (absolute value minus expectation)
        abs_z = abs(z_t)
        # E|z| depends on the innovation distribution (normal ≈ 0.7979,
        # Student-t heavier).  Scales the EGARCH shock term.
        shock_magnitude = abs_z - self._ez

        # One-step-ahead log-variance forecast
        log_var_new = (
            self.state.omega
            + self.state.alpha * shock_magnitude
            + self.state.gamma * z_t
            + self.state.beta * self.state.log_variance
        )

        # Soft-clip persistence to prevent explosion
        new_beta = self.state.beta
        if self.state.persistence > self.persistence_cap:
            new_beta *= self.persistence_cap / self.state.persistence

        # Compute prediction error for online gradient update.
        # EGARCH lives in log-variance space: the model predicts
        # log σ²_t, so the realized quantity must be a log-variance too
        # (log r_t²).  The old code subtracted the RAW squared return
        # (~1e-6 at bar scale) from log_variance (~-13) — a units
        # mismatch that made every gradient strongly positive and drove
        # omega (and the long-run variance) upward without bound,
        # inflating the 4-6h horizon bands ~300x.
        realized_log_var = 2.0 * math.log(max(abs(log_return), 1e-12))
        pred_error = realized_log_var - self.state.log_variance

        # Online parameter update (stochastic gradient)
        lr = self.learning_rate
        # Adaptive learning rate (RMSProp-style)
        grad_omega = pred_error
        grad_alpha = pred_error * shock_magnitude
        grad_gamma = pred_error * z_t
        grad_beta = pred_error * self.state.log_variance

        for name, grad in [("omega", grad_omega), ("alpha", grad_alpha),
                           ("gamma", grad_gamma), ("beta", grad_beta)]:
            # Update EMA of squared gradients
            self._grad_sq_ema[name] = 0.99 * self._grad_sq_ema[name] + 0.01 * grad ** 2

        # Apply updates with adaptive learning rate (RMSProp-style)
        self.state.omega += (lr / (math.sqrt(self._grad_sq_ema["omega"]) + 1e-8)) * grad_omega
        self.state.alpha = max(0.0, min(0.5, self.state.alpha + (lr / (math.sqrt(self._grad_sq_ema["alpha"]) + 1e-8)) * grad_alpha))
        self.state.gamma = max(-0.5, min(0.5, self.state.gamma + (lr / (math.sqrt(self._grad_sq_ema["gamma"]) + 1e-8)) * grad_gamma))
        self.state.beta = max(0.0, min(new_beta, 0.999))

        # Update state — clip for numerical stability (same bounds as calibration)
        self.state.log_variance = max(-30.0, min(5.0, log_var_new))
        self.state.long_run_variance = (
            math.exp(self.state.omega / (1.0 - self.state.persistence))
            if self.state.persistence < 1.0
            else self.state.long_run_variance
        )

        # Track z-score history for mean-reversion estimation
        self._z_history.append(z_t)
        if len(self._z_history) > self.mean_revert_lookback:
            self._z_history.pop(0)

        return self._build_features(z_t, sigma_t)

    def _build_features(self, z_t: float, sigma_t: float) -> dict[str, float]:
        """Build forecast feature dictionary."""
        forecast_var = self.state.conditional_variance
        forecast_sigma = self.state.conditional_volatility

        # Z-score: how extreme is current return vs forecast vol
        garch_z = z_t

        # Vol regime classification
        vol_ratio = forecast_sigma / max(self.state.long_run_vol, 1e-10)
        if vol_ratio < self.vol_regime_low:
            vol_regime = 0.0  # low
        elif vol_ratio > self.vol_regime_high:
            vol_regime = 2.0  # high
        else:
            vol_regime = 1.0  # normal

        # Mean-reversion probability:
        # When |z| > 2, vol tends to mean-revert.  The probability increases
        # with the number of consecutive extreme z-scores.
        mr_signal = self._compute_mean_revert_signal(z_t)

        # Persistence indicator: how long until vol shock decays by half
        persistence = self.state.persistence
        half_life = self.state.half_life

        return {
            "garch_forecast": forecast_var,
            "garch_sigma": forecast_sigma,
            "garch_sigma_annualized": forecast_sigma * math.sqrt(252 * 24 * 4),  # annualized (4H bars)
            "garch_z_score": garch_z,
            "garch_persistence": persistence,
            "garch_half_life": min(half_life, 999.0),
            "garch_vol_regime": vol_regime,
            "garch_vol_ratio": vol_ratio,
            "garch_mean_revert_signal": mr_signal,
            "garch_long_run_vol": self.state.long_run_vol,
            "garch_alpha": self.state.alpha,
            "garch_gamma": self.state.gamma,
        }

    def _compute_mean_revert_signal(self, z_t: float) -> float:
        """Estimate probability that volatility will mean-revert.

        Uses the empirical observation that after extreme z-scores (|z|>2),
        the next few observations tend to have lower z-scores.  The signal
        ranges from 0.0 (no reversion expected) to 1.0 (strong reversion).
        """
        if len(self._z_history) < 5:
            return 0.0

        # Count recent extreme z-scores
        recent_extremes = sum(1 for z in self._z_history[-10:] if abs(z) > 2.0)

        # Current extremity
        abs_z = abs(z_t)

        if abs_z < 1.0:
            # Already calm — no reversion signal
            return 0.0
        elif abs_z < 2.0:
            # Mild — weak reversion signal if history shows clustering
            return min(0.3, recent_extremes * 0.05)
        elif abs_z < 3.0:
            # Strong — moderate reversion signal
            return min(0.6, 0.3 + recent_extremes * 0.05)
        else:
            # Extreme — strong reversion signal (generator will pull back)
            return min(0.9, 0.5 + recent_extremes * 0.07)

    def _default_features(self) -> dict[str, float]:
        """Return neutral features during warmup phase."""
        return {
            "garch_forecast": self.state.long_run_variance,
            "garch_sigma": math.sqrt(self.state.long_run_variance),
            "garch_sigma_annualized": math.sqrt(self.state.long_run_variance) * math.sqrt(252 * 24 * 4),
            "garch_z_score": 0.0,
            "garch_persistence": self.state.persistence,
            "garch_half_life": self.state.half_life,
            "garch_vol_regime": 1.0,
            "garch_vol_ratio": 1.0,
            "garch_mean_revert_signal": 0.0,
            "garch_long_run_vol": self.state.long_run_vol,
            "garch_alpha": self.state.alpha,
            "garch_gamma": self.state.gamma,
        }

    def get_forecast(self) -> dict[str, float]:
        """Get current forecast features without updating (read-only)."""
        sigma_t = self.state.conditional_volatility
        return self._build_features(0.0, sigma_t)

    # ── Persistence ────────────────────────────────────────────────

    def save(self, path: str | Path) -> None:
        """Persist model state to JSON."""
        data = {
            "learning_rate": self.learning_rate,
            "min_observations": self.min_observations,
            "persistence_cap": self.persistence_cap,
            "vol_regime_low": self.vol_regime_low,
            "vol_regime_high": self.vol_regime_high,
            "mean_revert_lookback": self.mean_revert_lookback,
            "buffer_size": self._buffer_size,
            "distribution": self.distribution,
            "dof": self.dof,
            "state": self.state.to_dict(),
            "z_history": self._z_history[-self.mean_revert_lookback:],
            "grad_sq_ema": self._grad_sq_ema,
            "return_buffer": self._return_buffer[-self._buffer_size:],
        }
        Path(path).write_text(json.dumps(data, indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> EGARCHVarianceForecaster:
        """Restore model state from JSON."""
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        forecaster = cls(
            learning_rate=data["learning_rate"],
            min_observations=data["min_observations"],
            persistence_cap=data["persistence_cap"],
            vol_regime_low=data["vol_regime_low"],
            vol_regime_high=data["vol_regime_high"],
            mean_revert_lookback=data["mean_revert_lookback"],
            buffer_size=data.get("buffer_size", 50),
            distribution=data.get("distribution", "normal"),
            dof=data.get("dof", 5.0),
        )
        forecaster.state = GARCHState.from_dict(data["state"])
        forecaster._z_history = data.get("z_history", [])
        forecaster._grad_sq_ema = data.get("grad_sq_ema", forecaster._grad_sq_ema)
        forecaster._return_buffer = data.get("return_buffer", [])
        return forecaster
